# Generated by Django 3.2.13 on 2022-06-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=100)),
                ('heigth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weigth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_stats', models.TextField()),
                ('preevolution_id', models.IntegerField()),
                ('evolution_id', models.IntegerField()),
            ],
        ),
    ]
